### ISSUE TITLE
Serve Error

### ISSUE THREAD

**Issue by pw17l008** [ultrasonicsoft/ng-openstreetmap-demo#1]
Hi there!

I was trying to serve this app but was bombarded with a number of errors. 

Could not find module "@angular-devkit/build-angular" from "/Users/username/Downloads/ng-openstreetmap-demo-master".
Error: Could not find module "@angular-devkit/build-angular" from "/Users/username/Downloads/ng-openstreetmap-demo-master".
    at Object.resolve (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/core/node/resolve.js:141:11)
    at Observable.rxjs_1.Observable [as _subscribe] (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect.js:132:40)
    at Observable._trySubscribe (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:43:25)
    at Observable.subscribe (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:29:22)
    at DoOperator.call (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/tap.js:29:23)
    at Observable.subscribe (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:24:22)
    at /usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeTo.js:22:31
    at Object.subscribeToResult (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:75:38)
    at MergeMapSubscriber._tryNext (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:72:14)

Not sure if I'm missing something or its the App. 

Thanks!

**Comment by ghost** [comment]
Try running an `npm install` then if that completes without errors you should be able to do an `npm start`

Good luck!

**Comment by ultrasonicsoft** [comment]
Thanks @peteschaber
